# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- release/*
- beta/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  branchName: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]


steps:
- task: NuGetToolInstaller@1

- powershell: |
    if ('$(branchName)' -like 'release/*') {
      $version = '$(branchName)'.Substring(8) + ".$(Build.BuildId)"
    } elseif ('$(branchName)' -like 'beta/*') {
      $version = '$(branchName)'.Substring(5) + "-beta.$(Build.BuildId)"
    } else {
      $version = "0.0.0.$(Build.BuildId)"
    }
    Write-Host "##vso[task.setvariable variable=version]$version"
  displayName: 'Set Package Version'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    includesymbols: true
    includesource: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'version'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetAuthenticate@1
  inputs:
    nuGetServiceConnections: 'Nuget Service Connection'
    
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget Service Connection'